### ISSUE TITLE
Provide ontology in a FAIR format

### ISSUE THREAD

**Issue by stain** [go-fair-ins/GO-FAIR-Ontology#1]
I am unable to open the [`GO FAIR Ontology.vpp`](https://github.com/go-fair-ins/GO-FAIR-Ontology/blob/master/GO%20FAIR%20Ontology.vpp) ontology file. Does this product-specific format comply with the below?

> To be Interoperable:
> * I1. (meta)data use a formal, accessible, shared, and broadly applicable language for knowledge > representation.
> * I2. (meta)data use vocabularies that follow FAIR principles
> * I3. (meta)data include qualified references to other (meta)data

**Comment by stain** [comment]
```
(base) stain@biggie:~/Downloads$ file GO\ FAIR\ Ontology.vpp 
GO FAIR Ontology.vpp: SQLite 3.x database, last written using SQLite version 3008006
```

**Comment by roper79** [comment]
Hello @stain, the .vpp file is the Visual Paradigm format as indicated in the read.me.
